### ISSUE TITLE
Missing rows prediction

### ISSUE THREAD

**Issue by AI-paltan** [deepdoctection/deepdoctection#113]
row and column detection model missing onto some rows. Because of which end result of HTML table does not contain the contents of that row. Any possible workaround to add missing rows after?

**Comment by JaMe76** [comment]
There is no work around for adding missing rows or correcting predictions. You need to do this by hand after processing.

However, there are various config options available that you might tweak to get better results for your type of documents your are dealing with. The configuration was adjusted to achieve as few crashes in the analyzer process as possible. But it does not mean they are optimal for your use case. 

In conf_dd_one.yaml increase:
      
     SEGMENTATION.IOU_THRESHOLD_ROWS or 
     SEGMENTATION.IOA_THRESHOLD_ROWS.

You will also need to increase the config setting in row predictor, e.g. 

    MODEL.ROI_HEADS.NMS_THRESH_TEST for Pytorch. config file: CASCADE_RCNN_R_50_FPN_GN.yaml

   or 

    OUTPUT.FRCNN_NMS_THRESH for Tensorflow. config file: conf_frcnn_rows-yaml

For documents that differ from the training set, the analyzer tends to propose too many rows. In order to deal with that situation, the segmentation removes rows with low confidence score and intersection with other rows.  

I am currently preparing integration of https://github.com/microsoft/table-transformer . It will be ready in a couple of days and will allow you to try another model. 

These are the options if you do not want to fine tune the model on your own data.

**Comment by jayeshthukarul** [comment]
Thanks.
One logic I am thinking is like finding predicted cells which are not overlapped with predicted rows and for non overlapped cells will add row bounding box by taking reference of non overlapped cells position.
Let me try this logic and will confirm if it is working or not and will post code if it is working.

**Comment by jayeshthukarul** [comment]
One logic I am thinking is like finding predicted cells which are not overlapped with predicted rows and for non overlapped cells will add row bounding box by taking reference of non overlapped cells position.
Let me try this logic and will confirm if it is working or not and will post code if it is working.
