### ISSUE TITLE
Changing the categories in the layout detection

### ISSUE THREAD

**Issue by pcschreiber1** [deepdoctection/deepdoctection#211]
**Bug** 💥
I cannot seem to stop the layout detector from detecting "lists".

**Expected behavior**  🧮 
When I remove a layout category in the `ImageLayoutService`, it should no longer be detected.

I.e., from the tutorial the default `analyer` has 5 categories and I remove the category list.
```
analyzer = dd.get_dd_analyzer()

categories_layout = {"1": "text", "2": "title", "3": "table", "4": "figure"}

analyzer.pipe_component_list[0].predictor.categories = categories_layout

df = analyzer.analyze(path = "upload/resources/input/17_The-Labor-Act-2017-2074.pdf")
df.reset_state()                 # Trigger some initialization

doc = iter(df)
page = next(doc) 
```
Page should not contain "list" layouts. However, this is not the case. (I only recently started working with the library, so my expectation might be incorrect):

**Screenshots** 🖼
The deep purple is a "list". 
![image](https://github.com/deepdoctection/deepdoctection/assets/82368796/476a1f97-8772-4721-965e-b36a712c1ca0)
![image](https://github.com/deepdoctection/deepdoctection/assets/82368796/e1b17417-8072-45b0-a8da-781e3606227b)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: WSL2 on Windows.

**Additional context** 🧬
Thank you very much for this great package!

**Comment by JaMe76** [comment]
Thanks for the question. The problem is that the category dict is not getting used due to a further transformation here:

https://github.com/deepdoctection/deepdoctection/blob/869557de37f73ad5776a7a26b1909e1f0f93f2c6/deepdoctection/extern/d2detect.py#L197

Under the hood there is `self._categories_d2` being used. So you need to change this variable. 

However, just ignore the list label will result in a crash and you cannot do this in that way. If you want to filter any detected list element, then you can use the config file of the analyzer:

```
PT:
   LAYOUT:
      WEIGHTS: layout/d2_model_0829999_layout_inf_only.pt
      FILTER:
          - list
```

If you want to re-label list elements e.g. as text, then you can overwrite the category names 

```
categories={
                "1": LayoutType.text,
                "2": LayoutType.title,
                "3": LayoutType.text,
                "4": LayoutType.table,
                "5": LayoutType.figure,
            }

analyzer.pipe_component_list[0].predictor._categories_d2 = categories
```

But you need to keep all category-ids the model can predict in your dict.

**Comment by pcschreiber1** [comment]
Thank you for the explanation! My hope was that I could get the model to split up the large list layouts into smaller text layouts. But I guess I would need to find a different layout detection model then.
