### ISSUE TITLE
Sorting the page in the order including tables 

### ISSUE THREAD

**Issue by kethan52** [deepdoctection/deepdoctection#223]
Is there any way where we can sort the total information in the way it was on the page? I've tried various methods but failed to do that. please share the code if you have 

thankyou

**Comment by JaMe76** [comment]
So there is a text ordering algorithm but I understand that it seems to fail. 
Text ordering is based on a couple of rules that cannot cover every layout. 
To help you more I need more info, what is going wrong and especially what do you mean with sorting. Many layouts require to segment text but different segments can be regarded as independent which is why text sorting can be done in various ways.

**Comment by kethan52** [comment]
Per suppose I've uploaded a page and I need the output text in the same way it was present in the table ![download (3).png](https://github.com/deepdoctection/deepdoctection/assets/41123619/adce1ed9-632a-4169-aadb-35d48a83635c)
For this image I need the output text as title,text, text,text,title ,text ,text ,text,title,title,table,table information. In the same order of the page's input.

**Comment by JaMe76** [comment]
This is basically what deepdoctection does for text ordering. 
The algorithm, however, is rule based. It will not work for all document layout types.

To get text in reading order but with layout segments (e.g. title, text, ...) I suggest looking at [this discussion](https://github.com/deepdoctection/deepdoctection/discussions/83). 

You can also configure the text order algorithm. Check [this notebook](https://github.com/deepdoctection/notebooks/blob/main/Analyzer_Configuration.ipynb) for more information.  
Please note, that you might not always want to have all layout items to be considered (e.g. if you want to separate narrative text and tables). 

This is configurable as well.
