### ISSUE TITLE
Install Issue in Linux for deepdoctection[pt]

### ISSUE THREAD

**Issue by siddheshgunjal** [deepdoctection/deepdoctection#227]
**Bug** 💥
Trying to install deepdoctation in my conda environment with `pip install deepdoctection[pt]`. But fails with `Failed to build wheel` error for fasttext. I have also tried to resolve this fasttext install issue with `pip install fasttext-wheel`. But still no success. I tried with different python version: `3.11`, `3.10`, `3.8.18`, but failed in every python version.

**Expected behavior**  🧮 
Ideally `pip install deepdoctection[pt]` should have installed all the dependencies required for deepdoctection without any issue

**Screenshots** 🖼
![Screenshot from 2023-09-16 10-43-06](https://github.com/deepdoctection/deepdoctection/assets/37741186/10fb1ec5-96d2-42a0-9366-51810e73224e)
It fails with `ERROR: Could not build wheels for fasttext, which is required to install pyproject.toml-based projects` as seen in screenshot

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Fedora-Linux
 - Python versions tried: 3.11, 3.10, 3.8.18

**Additional context** 🧬
Docker build also fails on HuggingFace workspace, so I'm not able to create a sample output.

**Comment by JaMe76** [comment]
Seems that your gcc compiler cannot be found. But it is needed to build a fastetet wheel (and a Detectron2 wheel as well).

In many cases this can be fixed by installing the python-dev package. But I also suggest to have a look [here](https://linuxhint.com/error-command-gcc-failed-exit-status-1/).

Try with Python 3.8 or 3.10. I haven’t tried with 3.11 yet.
