### ISSUE TITLE
DocTr Input Error during Analyzer and File Saving Query

### ISSUE THREAD

**Issue by Dipankar1997161** [deepdoctection/deepdoctection#247]
@JaMe76,  Hey I closed other thread since I solved the issues I was facing.  I want to put forward another question. 

So I build the analyzer using both Tessaract and DocTr,  But the DocTr one directly doesn't take input as pdf??  When I  run on images, the output is clean, but when I run on pdfs, I got this error of ROI 

#### Q1.  So, is it advisable to convert the pdfs into individual jpg images before passing to the pipeline of DocTr??    IF so,  Which library will you recommend, since there are many .

<img width="1217" alt="Screenshot 2023-10-30 at 03 41 25" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/535e6653-c1f9-49fc-a23a-9b06ac896a70">

#### Q2.  How can I convert the given output of the analyzer into a CSV??  

I got these results in html.

<img width="853" alt="Screenshot 2023-10-30 at 03 54 15" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/b91c972a-7697-4e8a-8cd1-1145bd5a89ed">

Does DeepDoctection has any inbuilt function or anything to support the CSV save? or to create a data frame and then save it to CSV??

Do update me on this matter

**Comment by JaMe76** [comment]
> So I build the analyzer using both Tessaract and DocTr, But the DocTr one directly doesn't take input as pdf??

I am not sure what you mean. Are you building an analyzer by yourself? Or do you change the configs in order to use DocTr?
You cannot use both Tesseract and DocTr.

DocTr also works with PDFs because the analyzer internally converts all pdfs into np arrays using Poppler. 

> Q2. How can I convert the given output of the analyzer into a CSV??

Check [this notebook](https://github.com/deepdoctection/notebooks/blob/main/Get_Started.ipynb). There is advice for that.
