### ISSUE TITLE
Configuration not found after pip install deepdoctection[pt]

### ISSUE THREAD

**Issue by dannybusch** [deepdoctection/deepdoctection#25]
**Bug** 💥
Trying to replicate the example in the notebook. After running the following code line:

`analyzer = get_dd_analyzer(language="deu")`

I get an error message saying:

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/deepdoctection/configs/conf_dd_one.yaml'`

**Expected behavior**  🧮 
The analyzer will be returned and configured properly

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Linux
 - Env: Own docker image with all dependencies installed (detectron2, torch, torchvision, etc.)

**Additional context** 🧬
I cannot find the directory ./config/ in the site-packages/deepdoctection folder after the installation with 

`pip install deepdoctection[pt]`

**Workaround** :hot_pepper: 
I connected to my docker container and just ran:

```
git clone https://github.com/deepdoctection/deepdoctection.git
cd deepdoctection
pip install -e .
```
and then I could proceed with the example notebook provided.

**Comment by JaMe76** [comment]
Hello and thank you for pointing to the issue !

As the error message suggests the config file in question was not packed in release 0.11. A new release 0.12 has been created that can be downloaded from PyPi and which now includes the missing configs  (as well as some other small fixes that have been discovered since). 

I tested the new release and the notebook should be running now. 

Release 0.12 in line with 1a8475df4 .
