### ISSUE TITLE
Is there a way to delete detected line if inside a table segment?

### ISSUE THREAD

**Issue by domaschh** [deepdoctection/deepdoctection#255]
See in title?

I really like the project but I would like to merge lines with other bigger structures so that I don't read the text twice? Is this possible?

**Comment by JaMe76** [comment]
I would divide your question into two topics: Deduplication of words and configuring segmentation of larger text regions.

## Deduplication:

To avoid having words mapped to more than one layout structure you can set in the `conf_dd_one.yaml`:

 `MAX_PARENT_ONLY: True`. 

(This is the default value for a couple of weeks and will be updated in v.0.28)

With default config, words are mapped to layout segments by intersection of area  with a given threshold 0.6. If more than one layout segment intersect with a given word then you might have duplications. Modifying the config will assign one word only to the layout segment with highest ioa.

## Larger layout structures:

Currently, table regions go into table segmentation where cells, rows and columns are being detected. Rows and columns are only auxiliary structures to determine row/column numbers for cells. Words are mapped to cells due to the config:

```
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - text
    - title
    - list
    - cell
 ```

If you want to map words to tables instead, you can set:

```
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - text
    - title
    - list
    - table
```

Next, you need to order words within the table segment by setting:

```
TEXT_ORDERING:
  TEXT_BLOCK_CATEGORIES:
    - title
    - text
    - list
    - table
```

Note that this might cause problems when tables are complex because the reading order algorithm for rectangles is very simple just going from left to right/top to bottom.

**Comment by domaschh** [comment]
Thanks a lot for your help!
Also is there an easy way to instantiate an analyzer via another config.yaml file?  I jsut found the config_override list argument but not path to another config file. sth like dd.get_dd_analyzer(path='myconfig.yaml')? This would be a amazing because I foudn the example on huggingface where one can upload a single picture and get the annotated text a lot better than the defautl from get_analyzer(). https://huggingface.co/spaces/deepdoctection/deepdoctection Is that documentation saved somehwere and public?

Thanks a lot and greetings from Austria!

**Comment by JaMe76** [comment]
At the moment, you can only change the config by changing the original config file in your cache or using the `config_overwrite`. 
But having a path argument to an independent config is a good idea and I will use this issue as an enhancement.

The analyzer in the Huggingface space is a pipeline on its own. It uses different models for layout analysis/table recognition and Textract as OCR. These models are more precise on various layouts and therefore the configuration of nms/ioa must be changed as well.

Swapping is possible, however it is not documented and the reason is that I fear that this might result in more errors on the user side. It is not straight forward. Right now, you can swap models/remove components by changing the `.yaml` file.
