### ISSUE TITLE
Can't get dataset length when trying to train LayoutLm using funsd dataset

### ISSUE THREAD

**Issue by dvando** [deepdoctection/deepdoctection#256]
**Bug** 💥
I've got a bunch of MappingContextManager Errors when trying to train TokenClassification for LayoutLm. Details attached.

**Expected behavior**  🧮 
I'm trying to follow [this tutorial](https://github.com/deepdoctection/deepdoctection/blob/master/docs/tutorials/layoutlm_for_token_classification.md) but got this error.

**Screenshots** 🖼
![image](https://github.com/deepdoctection/deepdoctection/assets/63303799/0a93fcd9-4514-43f9-96cc-13676aaaa34b)
![image](https://github.com/deepdoctection/deepdoctection/assets/63303799/9ac137d7-de33-441e-9a30-51cd84b17716)
![image](https://github.com/deepdoctection/deepdoctection/assets/63303799/e4e20c6d-c31a-412b-ba1f-c376f2032514)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 20.04
 - Conda Environment
 - Installed the latest deepdoctection using Pytorch extension

**Additional context** 🧬
I tried to trace where the error came from, and since I could get the dataset length normally when it's still dataset instance, I suspect the error came from DatasetAdapter, though still has no idea how should I test it. Any insight would be appreciated, thanks in advance.

**Comment by JaMe76** [comment]
Thanks for reporting.

I am pretty sure that this issue is actually a duplicate of [this one](https://github.com/deepdoctection/deepdoctection/issues/241).

`MappingContextManager` catches an error and filters all images. This is the reason why you don't get any labels in your statistics. 

Why does the  `MappingContextManager` complain? I suspect because of this line:

https://github.com/deepdoctection/deepdoctection/blob/99409d9468d16a3338e2ed29f37f71e89a9bead6/deepdoctection/mapper/xfundstruct.py#L85

Funsd images are greyscaled images, e.g. 2-dimensional. For the same reason as #241 the (more recent) viz_handler cannot load these images and raises an error. After fixing this on my local machine the code runs smoothly. (Ok, I need to add a new dependency in order to let run the `Trainer`.

I will provide a within the next hours.

**Comment by dvando** [comment]
Sure, I'd like to try doing something about it too based on the new insight.

**Comment by dvando** [comment]
So I did a temporary workaround by using `opencv` in the `viz_handler` and change the `imread` method to use `cv2.IMREAD_UNCHANGED` flag, it works perfectly fine now. Should I close the issue or will you close it after making a PR about it?

**Comment by JaMe76** [comment]
You can close it. 

I am going to track everything with #241.

Thanks.

**Comment by dvando** [comment]
Sure, thanks a lot for the help.
