### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU          [[{{node pool0/MaxPool}}]]

### ISSUE THREAD

**Issue by Alevik02** [deepdoctection/deepdoctection#323]
After I installed TensorFlow and upgraded the typing-extensions in issue #322, most of the code I made previously doesn't work anymore.

The error that's given is (omitting the files's paths):
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node pool0/MaxPool}}]]
[...]
During handling of the above exception, another exception occurred:
[...]
raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:
[...]
Detected at node 'pool0/MaxPool' defined at (most recent call last):
[...]
Node: 'pool0/MaxPool'
Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node pool0/MaxPool}}]]
[...]
Original stack trace for 'pool0/MaxPool':
[...]
ret = Operation.from_node_def(

The code is (I am just using this code as an example):
import deepdoctection as dd
from matplotlib import pyplot as plt              

config_overwrite = ["USE_OCR=False", "USE_PDF_MINER=True" ]

analyzer = dd.get_dd_analyzer(config_overwrite=config_overwrite)  

df = analyzer.analyze(path = "./file.pdf)  

doc = iter(df)

for page in doc:    
    print(page.text)

The exception is raised when get_dd_analyzer is called.

**Comment by JaMe76** [comment]
- Can you specify your Tensorflow version ?
- Do you have a GPU available ?
- This Tensorflow implementation is quite old, e.g. taken from [here](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN). I adapted the code in order to make it work for TF2.  However, the implementation does not officially support plain CPU inference. The reason is we process NCWH tensors for which there is no implementation in older TF2 versions. You should get at least a logger warning that the models will not work. It seems that more recent TF version seem to support NCWH (at least it worked when I tried) but unfortunately I do not remember the version and for now I cannot ensure inference on CPU for these specific models.

**Comment by Alevik02** [comment]
- I installed Tensorflow 2.13.1
- The GPU should be avaiable (I am not sure)
