### ISSUE TITLE
NameError: name 'get_num_gpu' not defined.

### ISSUE THREAD

**Issue by Muhammad-Ibrahim-Khan** [deepdoctection/deepdoctection#53]
## **Bug** 💥
I have installed both PyTorch (since I'm using a CPU) and TensorFlow (because I need to load a model for another module). The system recognizes only TensorFlow unless I explicitly comment out the code that select TensorFlow in analyzer function.

## Solution
For The Analyzer, kindly create another arg which explicitly mentions which library to use e.g (backend="tensorflow" or "pytorch"). This way even if the developer has multiple libraries, one can select whichever he wishes to use.

**Comment by JaMe76** [comment]
Hi, thank you very much the report as well as for your suggestion.

I think your code breaks because even though Tensorflow has been installed you do follow the PyTorch installation process which in turn means that the Tensorflow support package Tensorpack is not available in your environment. Hence `get_num_gpu` cannot be found. 

Adding another argument in `get_dd_analyzer` to force framework selection is something I would refrain from doing as it will end up having arguments that do not relate to the analyzer configuration. 

What I can do on the other hand is adding an extra condition.

```
def _auto_select_lib_and_device() -> Tuple[str, str]:

    if tf_available() and tensorpack_available():  # avoiding crash if Tensorpack is not installed 
        if get_num_gpu() >= 1:
            return "tf", "cuda"   # use TF if GPU is available
        if pytorch_available():
            return "pt", "cpu"   # else use CPU
        raise ImportError()

    if pytorch_available():
        if cuda.is_available():
            return "pt", "gpu"
        return "pt", "cpu"
```

Let me know, if this will work for you.

**Comment by Muhammad-Ibrahim-Khan** [comment]
First of all, thank you for your reply.
That would be great. I'd have contributed myself but since I'm not familiar with all other dependencies I figured I'd open a bug request and see what the developers would have to say about this.
Thank you.

**Comment by JaMe76** [comment]
I've merged a fix to master. Feel free to check, if this works for you.
