### ISSUE TITLE
Error: Current process got forked after parallelism has been used.

### ISSUE THREAD

**Issue by Muhammad-Ibrahim-Khan** [deepdoctection/deepdoctection#88]
**Bug** 💥
My program has several APIs (Flask) which use fast_tokenizer of transformers library alongside multi-threading (Joblib) to speed up execution. However, while calling deep_doctection (using torch), I get the error whose screenshot is pasted below. Deep Doctection is not using fast_tokenizer and so analyzer.analyze should work fine.
**Important** : This issue only occurs when deployed using Docker, local runs always run fine.

**Screenshots** 🖼
![Screenshot from 2022-11-29 11-17-44](https://user-images.githubusercontent.com/97872563/204453581-165329ca-0bf6-4b7b-a56b-0a764611dc24.png)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 22.04.1 LTS
 - 16 Gb RAM

**Additional context** 🧬
Using the following:
- Python 3.9
- Flask for API
- Joblib for Multi-threading.
- Transformers (4.24.0)
- Tokenizers (0.13.2)
- Docker (Latest)

**Comment by JaMe76** [comment]
Hi,

when you mention to `analyzer.analyze` do you refer to the built-in `analyzer` generated from the factory `get_dd_analyzer` ? Or did you build a custom pipeline ? 

The reason I ask is that, while it is true that the `analyzer` from the factory does not use any components from the transformer/tokenizer library, there are some deepdoctection components who use them (check the notebook Using_LayoutLM_for_sequence_classification.ipynb) and they even require to use fast tokenizers. 

I do not know at what stage the tokenizer library starts its multi-threading, but if it is when importing the library then this will cause problems because e.g.

```python
import get_dd_analyzer
```
requires
 
```python
import ...pipe
```

requires 

```python
import ..mapper.laylmstruct
```

requires

```python
if transformers_available():
    from transformers import PreTrainedTokenizerFast
```

and because you mention, that you use fast tokenizers the condition ` transformers_available()` is satisfied. There are some other deepdoctection modules that require fast tokenizers as well. (On the other hand, just when writing this I doubt that this might be the reason as all modules are lazy modules and will only be executed when first used). 

Did you try to follow the tokenizer suggestion in your suggestion to set the environment variable `TOKENIZERS_PARALLELISM` to `False` ? 

Also remarkable your remark that everything works fine on local installation but not on Docker.

**Comment by Muhammad-Ibrahim-Khan** [comment]
Thank you for your reply.

1) I'm using the built-in pipeline (get_dd_analyzer).
2) I would like to keep the environment variable TOKENIZERS_PARALLELISM to be True otherwise I won't be able to use 'use_fast' in other APIs.
3) Docker images did have an issue with previous versions of tokenizers and while fast tokenizers would work locally, they'd create an issue inside a docker container (process forks) but the latest build (for transformers and tokenizers) apparently fixed this issue.
However, a quick fix does work (The one you mentioned above) but I was hoping that I'd keep fast tokenizers (the inference time decreases ten fold).

**Comment by JaMe76** [comment]
Thank you for the info.

Do you have any GH issue/communication at hand for 3.) ?

I understand that  `TOKENIZERS_PARALLELISM=False` is not optimal. However, I do not know yet where I could step in from my side in order to get it fixed.

But I understand, once 3.) is fixed it will also resolve this issue, right?

**Comment by Muhammad-Ibrahim-Khan** [comment]
That's the thing.
3). was fixed and runs as intended.

What I was hoping for is an option to not use fast_tokenizer within the analyzer instead of resorting to an environment variable.

Thank you for your time.
