### ISSUE TITLE
Requirements file seems not up to date

### ISSUE THREAD

**Issue by teuntjebrainial** [deepdoctection/deepdoctection#90]
**Bug** 💥
I kept getting errors when I tried to run the notebooks after installing the requirements in my virtual environment. Eventually I got it working with other package versions (see at screenshots section what versions I used) and some additional installations of other packages. Was this just me? Did I do anything wrong? 

**Expected behavior**  🧮 
I expected the repo to work when installing all the requirements

**Screenshots** 🖼
apted==1.0.3
    # via deepdoctection (setup.py)
attrs==21.4.0
    # via jsonlines
catalogue==2.0.7
    # via deepdoctection (setup.py)
certifi==2021.10.8
    # via requests
charset-normalizer==2.0.12
    # via requests
contourpy==1.0.5
    # via matplotlib
cycler==0.11.0
    # via matplotlib
distance==0.1.3
    # via deepdoctection (setup.py)
filelock==3.6.0
    # via huggingface-hub
fonttools==4.37.3
    # via matplotlib
huggingface-hub==0.11.0
    # via deepdoctection (setup.py)
idna==3.3
    # via requests
importlib-metadata==4.11.2
    # via deepdoctection (setup.py)
jsonlines==3.0.0
    # via deepdoctection (setup.py)
kiwisolver==1.4.4
    # via matplotlib
lxml==4.9.1
    # via deepdoctection (setup.py)
lxml-stubs==0.4.0
    # via deepdoctection (setup.py)
matplotlib==3.6.0
    # via pycocotools
mock==4.0.3
    # via deepdoctection (setup.py)
networkx==2.7.1
    # via deepdoctection (setup.py)
numpy==1.22.3
    # via
    #   contourpy
    #   deepdoctection (setup.py)
    #   matplotlib
    #   opencv-python
    #   pycocotools
opencv-python==4.5.4.60
    # via deepdoctection (setup.py)
packaging==21.3
    # via
    #   deepdoctection (setup.py)
    #   huggingface-hub
    #   matplotlib
pillow==9.2.0
    # via matplotlib
pycocotools==2.0.5
    # via deepdoctection (setup.py)
pyparsing==3.0.7
    # via
    #   matplotlib
    #   packaging
pypdf2==1.27.9
    # via deepdoctection (setup.py)
python-dateutil==2.8.2
    # via matplotlib
pyyaml==6.0
    # via
    #   deepdoctection (setup.py)
    #   huggingface-hub
pyzmq==24.0.1
    # via deepdoctection (setup.py)
requests==2.27.1
    # via huggingface-hub
six==1.16.0
    # via python-dateutil
tabulate==0.8.10
    # via deepdoctection (setup.py)
termcolor==2.0.1
    # via deepdoctection (setup.py)
tqdm==4.63.0
    # via huggingface-hub
types-pyyaml==6.0.8
    # via deepdoctection (setup.py)
types-tabulate==0.8.9
    # via deepdoctection (setup.py)
types-termcolor==1.1.3
    # via deepdoctection (setup.py)
types-tqdm==4.64.6
    # via deepdoctection (setup.py)
typing-extensions==4.1.1
    # via huggingface-hub
urllib3==1.26.8
    # via requests
zipp==3.7.0
    # via importlib-metadata
tensorflow==2.10.1

tensorflow-addons==0.18.0
tesseract-ocr

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Hi, 

so I assume you installed the library with 

```
pip install -r requirements.txt
```
I have just re-checked, the requirements.txt is up-to-date, however I am pretty sure it is not doing what you expect it should do:

Looking at the diagram:


![requirements_deepdoctection](https://user-images.githubusercontent.com/50324223/204559173-dca3e088-8e42-4d0e-923e-60812cd1f4fb.jpg)

`requirements.txt` is listing all dependencies that are not listed in any box outside the deepdoctection layer (e.g. Tensorflow - with add-ons, Tesseract etc.). Therefore `requirements.txt` should only be used if you only want to install the deep-learning services by yourself in order to have as little dependencies as possible. Using the `requirements.txt` file will have the same install outcome as when using 

```
pip install deepdoctection
```

Instead, I recommend using the install-with-extras options, e.g. for TF

```
pip install deepdoctection[tf]
```

or the corresponding command when installing from source. 

Looking at the diagram again, you will then still have to install everything which is below the deepdoctection layer, however it will install everything that is above the layer. 

As you can choose between TF and PT adding a `requirements.txt` for all install options will certainly lead to more confusion.

Finally, looking at your requirement file I am not quite sure, how you get it run with 

```
huggingface-hub==0.11.0
```

as Huggingface has changes the API for downloading models which is why I downgrade the requirements to `>=0.4.0,<0.11.0` but anyway, happy that you managed to get it run.  

Feel free to ask, if there are any further questions.
